### PR TITLE
fix rollup error

### PR DESCRIPTION
**Pull request by arasabbasi**

### CODE REVIEW

**Comment by eligrey** [comment]
Could you go into more detail as to why you're using `Function(...)()` instead of `eval(...)` and also what rollup error this fixes?

**Comment by arasabbasi** [comment]
Hi,

Problem is that when we use rollup, then rollup tries to replace the this-object to undefined.

I described it here https://github.com/MrRio/jsPDF/issues/1533

Or in short: The this keyword is equivalent to undefined at the top level of an ES (6?) module, and will be rewritten by rollup.
https://github.com/rollup/rollup/issues/847

It would be great if you change it, so that it will result in less problems. Atleast I hope it :). 

Why not eval you ask. Good question. It works and I think I read the usage of "Function()" as a recommendated solution. But this is your decision. 
:)

**Comment by arasabbasi** [comment]
Btw:

This is identical to https://github.com/eligrey/FileSaver.js/pull/387

**Comment by eligrey** [comment]
I'm actually unsure what package manager even uses `this.content`. It was added by someone else, and you can entirely drop the two lines. If you update your commit to simply remove `|| this.content || this` I'll go ahead and merge this.

**Comment by arasabbasi** [comment]
I removed this.content() and this. I kept global, because global is used by nodejs. Hope this is how you can accept it :).

**Comment by arasabbasi** [comment]
I realize now:
In your FileSaver.js-Project there is a comment:

```
// `self` is undefined in Firefox for Android content script context
// while `this` is nsIContentFrameMessageManager
// with an attribute `content` that corresponds to the window
```

Maybe this.content is something you need for writing plugins for Firefox?

**Comment by arasabbasi** [comment]
Do you still want this changes? Depending on your decision I would modify Blob.js and FileSaver.js

**Comment by eligrey** [comment]
Seems like for best compatibility we should keep one of the this references (the one that wouldn't cause any ReferenceErrors). Please put `|| this` back at the end of the statement and then increment [the version number at the top of the script](https://github.com/eligrey/Blob.js/blob/master/Blob.js#L3) to 2018-01-12, and then I will merge.

**Comment by arasabbasi** [comment]
Hi eli,

I double-checked it:
`Function('return this')()` equals `this`

So it would be redundant to have  a last `|| this`

**Comment by arasabbasi** [comment]
So you want that I remove the this.content reference? Maybe some people use it? Waiting for your instructions.

**Comment by eligrey** [comment]
I'm not saying to just add `|| this`, I'm saying to remove both `Function()` calls. `|| this` will suffice.

**Comment by arasabbasi** [comment]
Thank you. How about FileSaver.js? I just added now the global-scope. Do you want me to remove this.content there too?

**Pull request merged**
